//Reg/Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USED_MAIL = 'USED_MAIL';
export const REG_SUCCESS = 'REG_SUCCESS';
//Profile
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const NAME_HANDLER_OK = 'NAME_HANDLER_OK';
export const SURNAME_HANDLER_OK = 'SURNAME_HANDLER_OK';
export const EMAIL_HANDLER_OK = 'EMAIL_HANDLER_OK';
export const POSITION_HANDLER_OK = 'POSITION_HANDLER_OK';
export const NICKNAME_HANDLER_OK = 'NICKNAME_HANDLER_OK';
export const VK_HANDLER_OK = 'VK_HANDLER_OK';
export const TELE_HANDLER_OK = 'TELE_HANDLER_OK';
export const GITHUB_HANDLER_OK = 'GITHUB_HANDLER_OK';
export const LOAD_IMG_SUCCESS = 'LOAD_IMG_SUCCESS';
export const LOAD_PROGRESS_SUCCESS = 'LOAD_PROGRESS_SUCCESS';
export const LOAD_URL_SUCCESS = 'LOAD_URL_SUCCESS';
export const NEW_NAME = 'NEW_NAME';
